### ISSUE TITLE
Not working with multiple AllowedIPs

### ISSUE THREAD

**Issue by Siroj42** [b-m-f/wg-pod#4]
When using multiple AllowedIPs like in a standard wireguard.conf file, e.g.

```
AllowedIPs = 192.168.42.0/24, 192.168.178.0/24
```

`wg-pod join` results in this error:

```
Error: problem when configuring WireGuard interface podman-4137677 in namespace cni-673da6a1-33a4-48fc-1e92-7091531fa383 with config /root/wireguard/homeassistant/wg0.conf
Unable to parse IP address: `'
```

**Comment by b-m-f** [comment]
Hi,

The error should be on https://github.com/b-m-f/wg-pod/blob/0e2a2aa91388b9dc389c47d0fd84f88ef97ea9b9/pkg/wireguard/wireguard.go#L115.

I don't have time at the moment.
The line is split into parts. Sine AllowedIPs could be multiple values it needs to be refactored into an array that takes those parts from a config line.

Later when allowing the IPs this needs to be done for each IP of the array.

If anyone wants to give it a shot just open a PR. I'm happy to review and help out there

**Comment by b-m-f** [comment]
@Siroj42 this is fixed now. Releasing the new version today
